### ISSUE TITLE
Wikidata/Wikipedia link count doesn't seem to work …

### ISSUE THREAD

**Issue by lehkost** [dracor-org/caldracor#2]
… according to the metadata table (``https://dracor.org/api/corpora/cal/metadata``).

**Comment by cmil** [comment]
The Wikipedia links are queried once a day for all corpora around (Berlin) noon. So if you add Wikidata IDs for plays, it may not be before the next day that the link count is updated respectively. The update is not triggered immediately when a TEI document is modified because it would result in a lot of unnecessary queries.

That said, I triggered a link count update manually. The metadata table should be up to date for now.

**Comment by lehkost** [comment]
¡Excelente, gracias! ;)
